### ISSUE TITLE
Is the example current?

### ISSUE THREAD

**Issue by lastmeta** [J0/phoenix_gen_socket_client#69]
```
>mix deps.get
warning: use Mix.Config is deprecated. Use the Config module instead
  config/config.exs:6

warning: use Mix.Config is deprecated. Use the Config module instead
  config/dev.exs:1

Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  cowboy 1.1.2
  cowlib 1.0.2
  gettext 0.13.1
  jason 1.1.2
  mime 1.1.0
  phoenix 1.3.0
  phoenix_pubsub 1.0.2
  plug 1.4.3
  poison 3.1.0
  ranch 1.3.2
  websocket_client 1.2.4
```

```
>iex -S mix phx.server
warning: use Mix.Config is deprecated. Use the Config module instead
  config/config.exs:6

warning: use Mix.Config is deprecated. Use the Config module instead
  config/dev.exs:1

[warning] Phoenix is unable to create symlinks. Phoenix' code reloader will run considerably faster if symlinks are allowed. On Windows, such can be done by starting the shell with "Run as Administrator".
[notice] Application example exited: Example.start(:normal, []) returned an error: shutdown: failed to start child: ExampleWeb.Endpoint
    ** (EXIT) shutdown: failed to start child: Phoenix.PubSub.PG2
        ** (EXIT) shutdown: failed to start child: Phoenix.PubSub.PG2Server
            ** (EXIT) an exception was raised:
                ** (UndefinedFunctionError) function :pg2.create/1 is undefined or private 
                    (kernel 8.1.3) :pg2.create({:phx, ExampleWeb.PubSub})
                    (phoenix_pubsub 1.0.2) lib/phoenix/pubsub/pg2_server.ex:43: Phoenix.PubSub.PG2Server.init/1
                    (stdlib 3.16.1) gen_server.erl:423: :gen_server.init_it/2
                    (stdlib 3.16.1) gen_server.erl:390: :gen_server.init_it/6
                    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
[notice] Application jason exited: :stopped
[notice] Application websocket_client exited: :stopped
[notice] Application phoenix_gen_socket_client exited: :stopped
[notice] Application cowboy exited: :stopped
[notice] Application cowlib exited: :stopped
[notice] Application ranch exited: :stopped
** (Mix) Could not start application example: Example.start(:normal, []) returned an error: shutdown: failed to start child: ExampleWeb.Endpoint
    ** (EXIT) shutdown: failed to start child: Phoenix.PubSub.PG2
        ** (EXIT) shutdown: failed to start child: Phoenix.PubSub.PG2Server
            ** (EXIT) an exception was raised:
                ** (UndefinedFunctionError) function :pg2.create/1 is undefined or private 
                    (kernel 8.1.3) :pg2.create({:phx, ExampleWeb.PubSub})
                    (phoenix_pubsub 1.0.2) lib/phoenix/pubsub/pg2_server.ex:43: Phoenix.PubSub.PG2Server.init/1
                    (stdlib 3.16.1) gen_server.erl:423: :gen_server.init_it/2
                    (stdlib 3.16.1) gen_server.erl:390: :gen_server.init_it/6
                    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

**Comment by J0** [comment]
Hey,

Thanks for the query! The example is dated - we'l look into updating it
